version: '3.7'

services:
  web:
    build: 
      context: ./PublicTransitDataReportingPortal
      dockerfile: Dockerfile.prod
    command: gunicorn TransitData.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/PublicTransitDataReportingPortal/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/PublicTransitDataReportingPortal/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume: