# Generated by Django 2.2.6 on 2020-01-16 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalsummary_report_status',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('cover_sheet_status', models.CharField(choices=[('With user', 'With user'), ('With WSDOT', 'With WSDOT'), ('Complete', 'Complete')], default='With user', max_length=80)),
                ('cover_sheet_submitted_for_review', models.BooleanField(default=False)),
                ('data_report_status', models.CharField(choices=[('With user', 'With user'), ('With WSDOT', 'With WSDOT'), ('Complete', 'Complete')], default='With user', max_length=80)),
                ('data_report_submitted_for_review', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Panacea.organization')),
            ],
            options={
                'verbose_name': 'historical summary_report_status',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='summary_report_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('cover_sheet_status', models.CharField(choices=[('With user', 'With user'), ('With WSDOT', 'With WSDOT'), ('Complete', 'Complete')], default='With user', max_length=80)),
                ('cover_sheet_submitted_for_review', models.BooleanField(default=False)),
                ('data_report_status', models.CharField(choices=[('With user', 'With user'), ('With WSDOT', 'With WSDOT'), ('Complete', 'Complete')], default='With user', max_length=80)),
                ('data_report_submitted_for_review', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Panacea.organization')),
            ],
            options={
                'unique_together': {('year', 'organization')},
            },
        ),
    ]
