# Generated by Django 2.2.6 on 2020-02-10 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Panacea.expense_source'),
        ),
    ]
