# Generated by Django 2.2.6 on 2020-01-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0002_historicalsummary_report_status_summary_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='summary_reporter',
            field=models.BooleanField(default=True),
        ),
    ]
