# Generated by Django 2.2.6 on 2020-01-16 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0003_organization_summary_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='cover_sheet_review_notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('note_area', models.CharField(choices=[('Address', 'Address'), ('Organization', 'Organization'), ('Service', 'Service')], max_length=80)),
                ('wsdot_note', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historicalcover_sheet',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('executive_officer_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('executive_officer_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('executive_officer_title', models.CharField(blank=True, max_length=50, null=True)),
                ('service_website_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Service website URL')),
                ('service_area_description', models.CharField(blank=True, max_length=500, null=True)),
                ('congressional_districts', models.CharField(blank=True, max_length=100, null=True)),
                ('legislative_districts', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_government', models.CharField(blank=True, max_length=100, null=True)),
                ('governing_body', models.TextField(blank=True, null=True)),
                ('tax_rate_description', models.CharField(blank=True, max_length=250, null=True)),
                ('transit_development_plan_url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Transit development plan URL')),
                ('intermodal_connections', models.TextField(blank=True, null=True)),
                ('fares_description', models.TextField(blank=True, null=True)),
                ('service_and_eligibility', models.TextField(blank=True, null=True, verbose_name='Service and eligibility description')),
                ('current_operations', models.TextField(blank=True, null=True)),
                ('revenue_service_vehicles', models.TextField(blank=True, null=True, verbose_name='Revenue service vehicles')),
                ('days_of_service', models.CharField(blank=True, max_length=250, null=True, verbose_name='Days of service')),
                ('monorail_ownership', models.CharField(blank=True, max_length=250, null=True)),
                ('community_planning_region', models.CharField(blank=True, max_length=50, null=True)),
                ('organization_logo', models.BinaryField(blank=True, editable=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical cover_sheet',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='cover_sheet',
            constraint=models.UniqueConstraint(fields=('organization',), name='unique_organization'),
        ),
        migrations.AddField(
            model_name='historicalcover_sheet',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcover_sheet',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Panacea.organization'),
        ),
        migrations.AddField(
            model_name='cover_sheet_review_notes',
            name='cover_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Panacea.cover_sheet'),
        ),
    ]
