# Generated by Django 2.2.6 on 2020-01-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0005_historicalcover_sheet_review_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historicalcover_sheet_review_notes',
        ),
    ]
