# Generated by Django 2.2.6 on 2020-01-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0007_auto_20200116_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cover_sheet_review_notes',
            old_name='cover_sheet',
            new_name='summary_report_status',
        ),
    ]
