# Generated by Django 2.2.6 on 2020-01-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0008_auto_20200121_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover_sheet_review_notes',
            name='summary_report_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Panacea.summary_report_status'),
        ),
    ]
