# Generated by Django 2.2.6 on 2020-01-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0010_auto_20200123_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover_sheet_review_notes',
            name='note_field',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='cover_sheet_review_notes',
            name='parent_note',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
