# Generated by Django 2.2.6 on 2020-01-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0011_auto_20200124_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover_sheet_review_notes',
            name='note_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Waiting', 'Waiting')], default='Open', max_length=50),
        ),
    ]
