# Generated by Django 2.2.6 on 2020-02-06 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0012_cover_sheet_review_notes_note_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='summary_organization_progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.BooleanField(default=False)),
                ('address_and_organization', models.BooleanField(default=False)),
                ('organization_details', models.BooleanField(default=False)),
                ('service_cover_sheet', models.BooleanField(default=False)),
                ('confirm_service', models.BooleanField(default=False)),
                ('transit_data', models.BooleanField(default=False)),
                ('revenue', models.BooleanField(default=False)),
                ('expenses', models.BooleanField(default=False)),
                ('ending_balances', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Panacea.organization')),
            ],
        ),
    ]
