# Generated by Django 2.2.6 on 2020-02-06 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panacea', '0013_summary_organization_progress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transit_data',
            unique_together={('year', 'transit_mode', 'transit_metric', 'organization', 'administration_of_mode')},
        ),
    ]
